/*
 * NewTimingConstraintDialog.java
 *
 * Created on April 30, 2009, 10:38 AM
 */
package ngat.oss.client.gui.dialog;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ngat.phase2.IInstrumentConfig;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class EditInstrumentConfigDialog extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger(EditInstrumentConfigDialog.class);
    
    public EditInstrumentConfigDialog(IInstrumentConfig instrumentConfig, boolean modal) {
        this.setModal(modal);
        initComponents();
        initComponents2(instrumentConfig);
        centerFrame();
        addListeners();
    }

    public IInstrumentConfig getInstrumentConfig() {
        return instrumentConfigEditorPanel.getInstrumentConfig();
    }

    private void centerFrame() {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        double hd = screenDimension.getHeight();
        double wd = screenDimension.getWidth();

        double yd = (hd - this.getBounds().getHeight()) / 2;
        double xd = (wd - this.getBounds().getWidth()) / 2;

        final int x = (int) xd;
        final int y = (int) yd;

        EventQueue.invokeLater(
                new Runnable() {

                    public void run() {
                        EditInstrumentConfigDialog.this.setLocation(x, y);
                    }
                });
    }

    private void addListeners() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
                try {
                    instrumentConfigEditorPanel.setInstrumentConfig(null, false, true);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    logger.error(ex);
                }

                EditInstrumentConfigDialog.this.setVisible(false);
                EditInstrumentConfigDialog.this.dispose();
            }
        });
    }

    private void initComponents2(IInstrumentConfig instrumentConfig) {
        try {
            instrumentConfigEditorPanel.setInstrumentConfig(instrumentConfig, false, true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
            ex.printStackTrace();
            logger.error(ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnSubmit = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        instrumentConfigEditorPanel = new ngat.beans.guibeans.InstrumentConfigEditorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Instrument Config");

        jbtnSubmit.setForeground(new java.awt.Color(255, 0, 0));
        jbtnSubmit.setText("Submit");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jbtnSubmit)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnCancel)
                .add(442, 442, 442))
            .add(instrumentConfigEditorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(instrumentConfigEditorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnSubmit)
                    .add(jbtnCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
// TODO add your handling code here:
    if (instrumentConfigEditorPanel.containsValidInstrumentConfig()) {
        this.setVisible(false);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Please make sure the instrument config fields are correctly populated");
    }
}//GEN-LAST:event_jbtnSubmitActionPerformed

private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
    try {
        instrumentConfigEditorPanel.setInstrumentConfig(null, false, true);
    } catch (Exception ex) {
        ex.printStackTrace();
        logger.error(ex);
    }
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_jbtnCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ngat.beans.guibeans.InstrumentConfigEditorPanel instrumentConfigEditorPanel;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSubmit;
    // End of variables declaration//GEN-END:variables
}
