/*
 * NewTimingConstraintDialog.java
 *
 * Created on April 30, 2009, 10:38 AM
 */
package ngat.oss.client.gui.dialog;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import javax.swing.JScrollPane;
import ngat.oss.client.gui.model.EphemerisTargetTableModel;
import ngat.oss.client.gui.model.GroupHistoryTableModel;
import ngat.phase2.IGroup;
import ngat.phase2.XEphemerisTarget;

/**
 *
 * @author  nrc
 */
public class GroupHistoryDialog extends javax.swing.JDialog {

    private static final String LINE_SEPERATOR = String.valueOf((char)10);
    
    private IGroup group;
    
    public  GroupHistoryDialog(IGroup group) {
        this.setModal(true);
        this.group = group;
        initComponents();
        
        centerFrame();
        addListeners();
        initComponents2();
    }

    private void initComponents2() {

        jtblHistoryItemsTable.getColumnModel().getColumn(0).setPreferredWidth(80);
        jtblHistoryItemsTable.getColumnModel().getColumn(1).setPreferredWidth(80);
        jtblHistoryItemsTable.getColumnModel().getColumn(2).setPreferredWidth(15);
        
    }

    private void centerFrame() {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        double hd = screenDimension.getHeight();
        double wd = screenDimension.getWidth();

        double yd = (hd - this.getBounds().getHeight()) / 2;
        double xd = (wd - this.getBounds().getWidth()) / 2;

        final int x = (int) xd;
        final int y = (int) yd;

        EventQueue.invokeLater(
                new Runnable() {

                    public void run() {
                        GroupHistoryDialog.this.setLocation(x, y);
                    }
                });
    }

    private void addListeners() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
                GroupHistoryDialog.this.setVisible(false);
                GroupHistoryDialog.this.dispose();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblHistoryItemsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Execution History");

        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jtblHistoryItemsTable.setModel(new GroupHistoryTableModel(group.getID()));
        jScrollPane1.setViewportView(jtblHistoryItemsTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                    .add(jbtnClose))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed

   this.setVisible(false);
   this.dispose();
}//GEN-LAST:event_jbtnCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JTable jtblHistoryItemsTable;
    // End of variables declaration//GEN-END:variables
}
