/*
 * NewTimingConstraintDialog.java
 *
 * Created on April 30, 2009, 10:38 AM
 */
package ngat.oss.client.gui.dialog;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ngat.astrometry.Position;
import ngat.astrometry.ReferenceFrame;
import ngat.oss.client.Phase2ModelClient;
import ngat.oss.exception.Phase2Exception;
import ngat.phase2.IProgram;
import ngat.phase2.ITarget;
import ngat.phase2.XExtraSolarTarget;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class MultipleTargetEntryDialog extends javax.swing.JDialog {

    static Logger logger = Logger.getLogger(MultipleTargetEntryDialog.class);

    private static final String LINE_SEPERATOR = String.valueOf((char) 10);
    private IProgram program;
    private ArrayList targetsList;

    public MultipleTargetEntryDialog(IProgram program) {
        this.setModal(true);
        this.program = program;
        initComponents();

        centerFrame();
        addListeners();

        this.setTitle("Multiple target entry for programme: " + program.getName());
    }

    private void centerFrame() {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        double hd = screenDimension.getHeight();
        double wd = screenDimension.getWidth();

        double yd = (hd - this.getBounds().getHeight()) / 2;
        double xd = (wd - this.getBounds().getWidth()) / 2;

        final int x = (int) xd;
        final int y = (int) yd;

        EventQueue.invokeLater(
                new Runnable() {

                    public void run() {
                        MultipleTargetEntryDialog.this.setLocation(x, y);
                    }
                });
    }

    private void addListeners() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
                MultipleTargetEntryDialog.this.setVisible(false);
                MultipleTargetEntryDialog.this.dispose();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnChooseTargetFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jbtnClose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfSelectedFilePath = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnGo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");

        jbtnChooseTargetFile.setText("Choose and validate Target File");
        jbtnChooseTargetFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChooseTargetFileActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 15));
        jLabel1.setText("This tool enables you to add multiple extra-solar targets to a programme in one single operation.");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel2.setText("1. Prepare a text file with the targets specified within that file in the following format:");

        jLabel3.setText("RA needs to be in the following format:");

        jTextField1.setEditable(false);
        jTextField1.setText("<Target_name> <RA> <DEC>");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setText("HH:MM:SS.sss");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("DEC needs to be in the following format:");

        jTextField3.setEditable(false);
        jTextField3.setText("DD:MM:SS.ss");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Make sure that there are spaces between Target_name, RA and DEC, and that the target name does not have spaces in it.");

        jLabel6.setText("e.g. The text file should look something like this:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("MyTarget1 22:33:48.313 -4:12:41.34\nMyTarget2 20:17:32.122 -13:53:22.43\nMyTarget3 19:27:59.223 1:59:33.22");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel7.setText("2. Click this button and use the file chooser to select your target file:");

        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("3. Your chosen file is:");

        jtfSelectedFilePath.setEditable(false);
        jtfSelectedFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSelectedFilePathActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel9.setText("4. Click 'GO' to start the upload process. Watch out for error messages.");

        jbtnGo.setText("GO");
        jbtnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGoActionPerformed(evt);
            }
        });

        jLabel10.setText("(The default values for Epoch and Frame are J2000 and FK5 respectively).");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel4))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 281, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .addContainerGap(412, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jbtnClose)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(19, 19, 19)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(layout.createSequentialGroup()
                                .add(28, 28, 28)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 451, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jLabel10))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(jLabel8)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jtfSelectedFilePath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                        .add(layout.createSequentialGroup()
                            .add(jLabel7)
                            .add(18, 18, 18)
                            .add(jbtnChooseTargetFile))))
                .add(22, 22, 22))
            .add(layout.createSequentialGroup()
                .add(175, 175, 175)
                .add(jbtnGo)
                .addContainerGap(641, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {jScrollPane1, jTextField1}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jLabel4)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel10)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jbtnChooseTargetFile))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jtfSelectedFilePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnGo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void deleteTarget(ITarget target) {
        Phase2ModelClient phase2ModelClient = Phase2ModelClient.getInstance();
        try {
            phase2ModelClient.deleteTarget(target.getID());
        } catch (Phase2Exception ex) {
            ex.printStackTrace();
            logger.error(ex);
            return;
        }
        JOptionPane.showMessageDialog(this, "Target deleted");
    }

    private void updateTarget(ITarget target) {
        if (target == null) {
            return;
        }

        try {
            Phase2ModelClient phase2ModelClient = Phase2ModelClient.getInstance();
            phase2ModelClient.updateTarget(target, 999);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "target  update failed: " + ex.getMessage());
            ex.printStackTrace();
            logger.error(ex);
        }
    }

private void jbtnChooseTargetFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChooseTargetFileActionPerformed

    JFileChooser chooser = new JFileChooser();

    int status = chooser.showDialog(null, "Load a list of targets from a file");

    File file = null;
    ArrayList errorsList = new ArrayList();
    targetsList = new ArrayList(); //clear the extant targets list

    if (status == JFileChooser.APPROVE_OPTION) {
            try {
                BufferedReader bin = null;
                //try {
                file = chooser.getSelectedFile();
                bin = new BufferedReader(new FileReader(file));
                String line = null;
                //quickly parse it to make sure it's okay
                while ((line = bin.readLine()) != null) {
                    StringTokenizer st = new StringTokenizer(line);
                    String name = st.nextToken();
                    String stra = st.nextToken();
                    String stdec = st.nextToken();
                    double ra = Position.parseHMS(stra, ":");
                    double dec = Position.parseDMS(stdec, ":");
                    ITarget targetFoundInDatabase = Phase2ModelClient.getInstance().findTarget(program.getID(), name);
                    if (targetFoundInDatabase != null) {
                        errorsList.add("Target " + name + " already exists on programme " + program.getName() + " change the name to add this target");
                    } else {
                        XExtraSolarTarget extraSolarTarget = new XExtraSolarTarget(name);
                        extraSolarTarget.setRa(ra);
                        extraSolarTarget.setDec(dec);
                        
                        //defaults
                        extraSolarTarget.setEpoch(2000);
                        extraSolarTarget.setFrame(ReferenceFrame.FK5);
                        
                        targetsList.add(extraSolarTarget);
                    }
                }
            } catch (ParseException ex) {
                errorsList.add("The file does not appear to be in the correct format.");
                ex.printStackTrace();
                logger.error(ex);
            } catch (IOException ex) {
                errorsList.add("The file could not be found, or could not be read.");
                ex.printStackTrace();
                logger.error(ex);
            }

            if (errorsList.isEmpty()) {
                jtfSelectedFilePath.setText(file.getAbsolutePath());
                JOptionPane.showMessageDialog(this, "The targets in the file validated successfully");
            } else {
                String e = "";
                Iterator eli = errorsList.iterator();
                while (eli.hasNext()) {
                    String m = (String) eli.next();
                    e += m + "\n";
                }
                JOptionPane.showMessageDialog(this,
                    "Some errors occurred:\n" + e,
                    "No targets will be added",
                    JOptionPane.ERROR_MESSAGE);
            }
    }
}//GEN-LAST:event_jbtnChooseTargetFileActionPerformed

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_jbtnCloseActionPerformed

private void jtfSelectedFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSelectedFilePathActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtfSelectedFilePathActionPerformed

private void jbtnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGoActionPerformed

    ArrayList errorsList = new ArrayList();

    Iterator tli = targetsList.iterator();
    while(tli.hasNext()) {
        try {
            XExtraSolarTarget extraSolarTarget = (XExtraSolarTarget) tli.next();
            Phase2ModelClient.getInstance().addTarget(program.getID(), extraSolarTarget);
        } catch(Exception e) {
            errorsList.add(e.getMessage());
            e.printStackTrace();
            logger.error(e);
        }
    }
       
    if (errorsList.isEmpty()) {
       JOptionPane.showMessageDialog(this, "The targets were added successfully");
       this.setVisible(false);
        this.dispose();
    } else {
        String e = "";
        Iterator eli = errorsList.iterator();
        while (eli.hasNext()) {
            String m = (String) eli.next();
            e += m + "\n";
        }
        JOptionPane.showMessageDialog(this, "Some errors occurred:\n" + e);
    }

}//GEN-LAST:event_jbtnGoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbtnChooseTargetFile;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnGo;
    private javax.swing.JTextField jtfSelectedFilePath;
    // End of variables declaration//GEN-END:variables
}
