/*
 * NewTimingConstraintDialog.java
 *
 * Created on April 30, 2009, 10:38 AM
 */
package ngat.oss.client.gui.dialog;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import ngat.phase2.ITarget;
import ngat.phase2.XEphemerisTarget;
import ngat.phase2.XExtraSolarTarget;
import ngat.phase2.XSlaNamedPlanetTarget;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class NewTargetDialog extends javax.swing.JDialog implements ActionListener {

    static Logger logger = Logger.getLogger(NewTargetDialog.class);

    //private ITimingConstraint timingConstraint;
    private static final String EPHEMERIS = "Ephemeris";
    private static final String EXTRA_SOLAR = "ExtraSolar";
    private static final String SLA_NAMED = "SlaNamed";
    private static final String STANDARD = "STandard";

    private boolean wasKilled = false;
    
    /** Creates new form NewTimingConstraintDialog */
    public NewTargetDialog(boolean modal) {
        this.setModal(modal);
        initComponents();
        initComponents2();
        centerFrame();
        addListeners();
    }
    
    public ITarget getTarget() {
        return targetEditorPanel.getTarget();
    }

    public void setTarget(ITarget target) throws Exception {
        targetEditorPanel.setTarget(target, true, false); //any edited target is not a standard
    }
    
    public boolean wasKilled() {
        return wasKilled;
    }
    
    private void centerFrame() {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        double hd = screenDimension.getHeight();
        double wd = screenDimension.getWidth();

        double yd = (hd - this.getBounds().getHeight()) / 2;
        double xd = (wd - this.getBounds().getWidth()) / 2;

        final int x = (int) xd;
        final int y = (int) yd;

        EventQueue.invokeLater(
                new Runnable() {

                    public void run() {
                        NewTargetDialog.this.setLocation(x, y);
                    }
                });
    }

    private void addListeners() {
        jrbEphemerisTarget.addActionListener(this);
        jrbExtraSolarTarget.addActionListener(this);       
        jrbSlaNamedPlanetTarget.addActionListener(this);
        jrbStandard.addActionListener(this);
    }

    private void initComponents2() {

        jrbEphemerisTarget.setActionCommand(EPHEMERIS);
        jrbExtraSolarTarget.setActionCommand(EXTRA_SOLAR);
        jrbSlaNamedPlanetTarget.setActionCommand(SLA_NAMED);
        jrbStandard.setActionCommand(STANDARD);
        
        ButtonGroup group = new ButtonGroup();
        group.add(jrbEphemerisTarget);
        group.add(jrbExtraSolarTarget);
        group.add(jrbSlaNamedPlanetTarget);
        group.add(jrbStandard);
    }

    public void actionPerformed(ActionEvent actionEvent) {
        String actionCommand = actionEvent.getActionCommand();
        ITarget target = null;

        boolean isStandard = false;
        
        if (actionCommand.equals(EPHEMERIS)) {
            target = new XEphemerisTarget();
        } else if (actionCommand.equals(EXTRA_SOLAR)) {
            target = new XExtraSolarTarget();
        } else if (actionCommand.equals(SLA_NAMED)) {
            target = new XSlaNamedPlanetTarget();
        } else if (actionCommand.equals(STANDARD)) {
            isStandard = true;
            target = new XExtraSolarTarget();
        }
        
        try {
            targetEditorPanel.setTarget(target, true, isStandard);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbEphemerisTarget = new javax.swing.JRadioButton();
        jrbExtraSolarTarget = new javax.swing.JRadioButton();
        jrbSlaNamedPlanetTarget = new javax.swing.JRadioButton();
        jrbStandard = new javax.swing.JRadioButton();
        jbtnCreate = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        targetEditorPanel = new ngat.beans.guibeans.TargetEditorPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Target Creation");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowClosingHandler(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Select target type"));

        jrbEphemerisTarget.setText("Ephemeris Target");

        jrbExtraSolarTarget.setText("Extra-Solar Target");

        jrbSlaNamedPlanetTarget.setText("Catalogue Target");

        jrbStandard.setText("Standard");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jrbExtraSolarTarget)
                    .add(jrbEphemerisTarget))
                .add(42, 42, 42)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jrbStandard)
                    .add(jrbSlaNamedPlanetTarget))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jrbExtraSolarTarget)
                    .add(jrbSlaNamedPlanetTarget))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jrbEphemerisTarget)
                    .add(jrbStandard))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnCreate.setForeground(new java.awt.Color(255, 0, 0));
        jbtnCreate.setText("Create");
        jbtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(3, 3, 3)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(targetEditorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(jbtnCreate)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jbtnCancel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 395, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(targetEditorPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnCreate)
                    .add(jbtnCancel)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateActionPerformed
// TODO add your handling code here:
    
    if (targetEditorPanel.containsValidTarget()) {
        this.setVisible(false);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Please make sure the target fields are correctly populated");
    }
}//GEN-LAST:event_jbtnCreateActionPerformed

private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
    try {
        setTarget(null);
    } catch (Exception ex) {
        ex.printStackTrace();
        logger.error(ex);
    }
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_jbtnCancelActionPerformed

private void windowClosingHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosingHandler
    wasKilled = true;
}//GEN-LAST:event_windowClosingHandler

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewTargetDialog dialog = new NewTargetDialog(true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnCreate;
    private javax.swing.JRadioButton jrbEphemerisTarget;
    private javax.swing.JRadioButton jrbExtraSolarTarget;
    private javax.swing.JRadioButton jrbSlaNamedPlanetTarget;
    private javax.swing.JRadioButton jrbStandard;
    private ngat.beans.guibeans.TargetEditorPanel targetEditorPanel;
    // End of variables declaration//GEN-END:variables

}
