/*
 * NewTimingConstraintDialog.java
 *
 * Created on April 30, 2009, 10:38 AM
 */
package ngat.oss.client.gui.dialog;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import ngat.oss.client.Phase2ModelClient;
import ngat.phase2.IProposal;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class ScienceAbstractDialog extends javax.swing.JDialog implements ActionListener {

    static Logger logger = Logger.getLogger(ScienceAbstractDialog.class);

    private IProposal proposal;

    public ScienceAbstractDialog(boolean modal, IProposal proposal) {
        this.setModal(modal);
        this.proposal = proposal;
        
        initComponents();
        initComponents2();
        this.setSize(new Dimension(700, 640));
        centerFrame();
        addListeners();
        this.setTitle("Science abstract of proposal " + proposal.getName());
    }

    public String getScienceAbstract() {
        return jtaSciAbstract.getText();
    }

    private void initComponents2() {
        
        String scienceAbstract = proposal.getScienceAbstract();
        jtaSciAbstract.setText(scienceAbstract);
    }
    
    private void centerFrame() {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        double hd = screenDimension.getHeight();
        double wd = screenDimension.getWidth();

        double yd = (hd - this.getBounds().getHeight()) / 2;
        double xd = (wd - this.getBounds().getWidth()) / 2;

        final int x = (int) xd;
        final int y = (int) yd;

        EventQueue.invokeLater(
                new Runnable() {

                    public void run() {
                        ScienceAbstractDialog.this.setLocation(x, y);
                    }
                });
    }

    private void addListeners() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
                ScienceAbstractDialog.this.setVisible(false);
                ScienceAbstractDialog.this.dispose();
            }
        });
    }

    public void actionPerformed(ActionEvent actionEvent) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSciAbstract = new javax.swing.JTextArea();
        jbtnEdit = new javax.swing.JButton();
        jbtnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accounts");
        setResizable(false);

        jbtnClose.setText("Close");
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        jtaSciAbstract.setColumns(20);
        jtaSciAbstract.setEditable(false);
        jtaSciAbstract.setRows(5);
        jScrollPane1.setViewportView(jtaSciAbstract);

        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnSubmit.setForeground(new java.awt.Color(255, 0, 0));
        jbtnSubmit.setText("Submit");
        jbtnSubmit.setEnabled(false);
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jbtnEdit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnSubmit))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .add(jbtnClose))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnEdit)
                    .add(jbtnSubmit))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
   
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_jbtnCloseActionPerformed

private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
    jtaSciAbstract.setEditable(true);
    jbtnSubmit.setEnabled(false);
    jbtnEdit.setEnabled(false);
}//GEN-LAST:event_jbtnEditActionPerformed

private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
   
    String scienceAbstract = jtaSciAbstract.getText();

    Phase2ModelClient phase2ModelClient = Phase2ModelClient.getInstance();
    
    //unncomment and write the following method to allow science abstract submission:
    /*
    try {
        IProposal proposalWithName = phase2ModelClient.updateScienceAbstractOfProposal(proposal.getID(), scienceAbstract);
    } catch (Phase2Exception ex) {
        ex.printStackTrace();
        logger.error(ex);
    }
    */
    jtaSciAbstract.setEditable(false);
    jbtnSubmit.setEnabled(false);
    jbtnEdit.setEnabled(true);
}//GEN-LAST:event_jbtnSubmitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JTextArea jtaSciAbstract;
    // End of variables declaration//GEN-END:variables
}
