/*
 * SelectSequenceTypePanel.java
 *
 * Created on June 11, 2009, 10:39 AM
 */

package ngat.oss.client.gui.panel;

import javax.swing.ButtonGroup;
import ngat.oss.client.gui.reference.Session;

/**
 *
 * @author  nrc
 */
public class SelectSequenceTypePanel extends javax.swing.JPanel {

    public static final String MULTI_COLOUR_PHOTOMETRY_WIZARD = "MULTI_COLOUR_WIZARD";
    public static final String POLARIMETRY_WIZARD = "POLARIMETRY_WIZARD";
    public static final String SPRAT_WIZARD = "SPRAT_WIZARD";
    public static final String FRODO_WIZARD = "FRODO_WIZARD";
    public static final String LOTUS_WIZARD = "LOTUS_WIZARD";
    public static final String MANUAL_SEQUENCE_EDITOR = "MANUAL_SEQUENCE_EDITOR";
    
    private ButtonGroup group;
    
    /** Creates new form SelectSequenceTypePanel */
    public SelectSequenceTypePanel() {
        initComponents();

        jrbMultiColourWizard.setActionCommand(MULTI_COLOUR_PHOTOMETRY_WIZARD);
        jrbPolarimetry.setActionCommand(POLARIMETRY_WIZARD);
        jrbSPRATWizard.setActionCommand(SPRAT_WIZARD);
        jrbFrodoWizard.setActionCommand(FRODO_WIZARD);
        jrbLOTUS.setActionCommand(LOTUS_WIZARD);
        jrbMultiColourSeqBuilder.setActionCommand(MANUAL_SEQUENCE_EDITOR);
        
        group = new ButtonGroup();
        group.add(jrbMultiColourWizard);
        group.add(jrbPolarimetry);
        
        group.add(jrbFrodoWizard);
        group.add(jrbLOTUS);
        group.add(jrbMultiColourSeqBuilder);
        group.add(jrbSPRATWizard);
        
    }

    public String getActionCommand() {
        return group.getSelection().getActionCommand();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbMultiColourWizard = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jrbFrodoWizard = new javax.swing.JRadioButton();
        jrbMultiColourSeqBuilder = new javax.swing.JRadioButton();
        jrbPolarimetry = new javax.swing.JRadioButton();
        jrbSPRATWizard = new javax.swing.JRadioButton();
        jrbLOTUS = new javax.swing.JRadioButton();

        jrbMultiColourWizard.setText("Wizard for Multicolour Photometry");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Select a method for building an observation sequence:");

        jrbFrodoWizard.setText("Wizard for FRODOSpec (Dual Beam Spectrograph)");

        jrbMultiColourSeqBuilder.setText("Manual Sequence Editor");

        jrbPolarimetry.setText("Wizard for Polarimetry");

        jrbSPRATWizard.setText("Wizard for SPRAT (Imaging Spectrograph)");

        jrbLOTUS.setText("Wizard for LOTUS (Two slit spectrograph)");
        jrbLOTUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLOTUSActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(65, 65, 65)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jrbMultiColourWizard)
                            .add(jrbSPRATWizard)
                            .add(jrbPolarimetry)
                            .add(jrbMultiColourSeqBuilder)
                            .add(jrbFrodoWizard)
                            .add(jrbLOTUS))))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(47, 47, 47)
                .add(jrbMultiColourWizard)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbPolarimetry)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbSPRATWizard)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbFrodoWizard)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbLOTUS)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbMultiColourSeqBuilder)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbLOTUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLOTUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLOTUSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jrbFrodoWizard;
    private javax.swing.JRadioButton jrbLOTUS;
    private javax.swing.JRadioButton jrbMultiColourSeqBuilder;
    private javax.swing.JRadioButton jrbMultiColourWizard;
    private javax.swing.JRadioButton jrbPolarimetry;
    private javax.swing.JRadioButton jrbSPRATWizard;
    // End of variables declaration//GEN-END:variables

}
