/*
 * ProgrammeHeaderPanel.java
 *
 * Created on March 27, 2009, 2:54 PM
 */
package ngat.oss.client.gui.panel;

import ngat.oss.client.AccountModelClient;
import ngat.phase2.IProposal;
import ngat.phase2.ISemester;
import ngat.phase2.ITag;
import ngat.phase2.XAccount;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class SemesterAccountPanel extends javax.swing.JPanel  {

    static Logger logger = Logger.getLogger(SemesterAccountPanel.class);

    private boolean enabled;
    private boolean editable;
    private AccountModelClient proposalAccountModelClient;
    private AccountModelClient tagAccountModelClient;

    private XAccount totalAccount;

    private ISemester semester;

    public SemesterAccountPanel() {

    }
    
    public SemesterAccountPanel(AccountModelClient proposalAccountModelClient,  AccountModelClient tagAccountModelClient, ISemester semester, boolean editable) {
        this.semester = semester;
        this.editable = editable;

        this.proposalAccountModelClient = proposalAccountModelClient;
        this.tagAccountModelClient = tagAccountModelClient;
        
        initComponents();
        try {
            populateComponents();
        } catch (Exception ex) {
            ex.printStackTrace();
            logger.error(ex);
        }
    }

    private void populateComponents() {

        SemesterAccountObjectsTablePanel semesterProposalsPanel = new SemesterAccountObjectsTablePanel(IProposal.class, semester, proposalAccountModelClient);
        jtpSemestersTabbedPane.addTab("Proposals", semesterProposalsPanel);

        SemesterAccountObjectsTablePanel semesterTAGsPanel = new SemesterAccountObjectsTablePanel(ITag.class, semester, tagAccountModelClient);
        jtpSemestersTabbedPane.addTab("TAGs", semesterTAGsPanel);

        jtpSemestersTabbedPane.setSelectedIndex(0);

    }


    public boolean isEnabled() {
        return enabled;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpSemestersTabbedPane = new javax.swing.JTabbedPane();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jtpSemestersTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jtpSemestersTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtpSemestersTabbedPane;
    // End of variables declaration//GEN-END:variables
    
}
