/*
 * MultiColourPhotomSequencePanel.java
 *
 * Created on June 11, 2009, 12:36 PM
 */
package ngat.oss.client.gui.panel;

import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.tree.TreeSelectionModel;
import ngat.oss.client.Phase2ModelClient;
import ngat.oss.client.gui.tree.sequencetree.ObservationSequenceTreeRenderer;
import ngat.oss.client.gui.tree.sequencetree.ObservationSequenceTreeModel;
import ngat.oss.exception.Phase2Exception;
import ngat.phase2.IGroup;
import ngat.phase2.IProgram;
import ngat.phase2.ISequenceComponent;

/**
 *
 * @author  nrc
 */
public class ShowObservationSequencePanel extends javax.swing.JPanel {

    /** Creates new form MultiColourPhotomSequencePanel */
    public ShowObservationSequencePanel(IGroup group) throws Phase2Exception {
        this(getSequenceComponentOfGroup(group));
    }

    public ShowObservationSequencePanel(ISequenceComponent sequenceComponent) {
        initComponents();
        populateComponents(sequenceComponent);
    }

    private void populateComponents(ISequenceComponent sequenceComponent) {
        loadTreeModel(sequenceComponent);
    }

    private static ISequenceComponent getSequenceComponentOfGroup(IGroup group) throws Phase2Exception {
        Phase2ModelClient phase2ModelClient = Phase2ModelClient.getInstance();
        ISequenceComponent sequenceComponent = phase2ModelClient.getObservationSequenceOfGroup(group.getID());
        return sequenceComponent;
    }
    
    private void loadTreeModel(ISequenceComponent sequenceComponent) {
        //instantiate a new DynamicUserTreeModel and place it in the Session
        //by default it will use the IUser in the Session to load its data
        ObservationSequenceTreeModel obsSeqTreeModel = new ObservationSequenceTreeModel(sequenceComponent);
       
        //set the model of the overview tree to be this model
        jtObsSequenceTree.setModel(obsSeqTreeModel);
        
        //set the selection to single item only selection
        int mode = TreeSelectionModel.SINGLE_TREE_SELECTION;
        jtObsSequenceTree.getSelectionModel().setSelectionMode(mode);
        //instantiate the MainTreeRenderer and add it as a renderer for the tree
        
        //HOOK THIS UP:
        jtObsSequenceTree.setCellRenderer(new ObservationSequenceTreeRenderer());
        
        //add listeners to tree events here if needed in future
        //jtObsSequenceTree.addTreeSelectionListener(new ObservationComponentSelector(jtObsSequenceTree,  this));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtObsSequenceTree = new javax.swing.JTree();

        jtObsSequenceTree.setModel(null);
        jScrollPane1.setViewportView(jtObsSequenceTree);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1376, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 537, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jtObsSequenceTree;
    // End of variables declaration//GEN-END:variables
}
