/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RotatorPanel.java
 *
 * Created on Sep 9, 2009, 10:19:07 AM
 */

package ngat.oss.client.gui.panel.sequencepanels;

import ngat.oss.client.gui.panel.*;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ngat.phase2.IExecutiveAction;
import ngat.phase2.ILampDef;
import ngat.phase2.ISequenceComponent;
import ngat.phase2.XArc;
import ngat.phase2.XExecutiveComponent;
import ngat.phase2.XLampDef;

/**
 *
 * @author nrc
 */
public class ArcPanel extends javax.swing.JPanel implements SequenceComponentPanel {

    /** Creates new form RotatorPanel */
    public ArcPanel() {
        initComponents();
    }

    public ArcPanel(XArc arc) {
        this();
        
        ILampDef lamp = arc.getLamp();

        if (lamp.getLampName().equalsIgnoreCase("Ne")) {
            JOptionPane.showMessageDialog(this, "Ne is no longer the preferred lamp on FRODOSpec for Arcs");
        } else {
            jcbLampName.setSelectedItem(lamp.getLampName());
        }
    }

    public ISequenceComponent getSequenceComponent() {

        //currently assumes that the exposure type is a XMultipleExposure
        XArc arc = new XArc();
        String lampName = (String)jcbLampName.getSelectedItem();
        arc.setLamp(new XLampDef(lampName));
        
        return new XExecutiveComponent("ARC",(IExecutiveAction) arc);
    }

    public boolean isValidData() {
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jcbLampName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("Arc");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcbLampName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Xe", "W" }));

        jLabel5.setText("Lamp:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .add(64, 64, 64)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcbLampName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jcbLampName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
            JFrame j = new JFrame();
            j.getContentPane().setLayout(new BorderLayout());
            j.getContentPane().add(new ArcPanel(), BorderLayout.CENTER);
            j.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcbLampName;
    // End of variables declaration//GEN-END:variables

}
