/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AutoguidePanel.java
 *
 * Created on Sep 9, 2009, 10:59:54 AM
 */

package ngat.oss.client.gui.panel.sequencepanels;

import ngat.oss.client.gui.panel.*;
import javax.swing.ButtonGroup;
import ngat.phase2.IAutoguiderConfig;
import ngat.phase2.IExecutiveAction;
import ngat.phase2.ISequenceComponent;
import ngat.phase2.XAutoguiderConfig;
import ngat.phase2.XExecutiveComponent;

/**
 *
 * @author nrc
 */
public class AutoguidePanel extends javax.swing.JPanel implements SequenceComponentPanel {

    private static final String CMD_NO = "AUTOGUIDE_NO";
    private static final String CMD_YES = "AUTOGUIDE_YES";
    private static final String CMD_AUTO = "AUTOGUIDE_AUTO";

    private ButtonGroup buttonGroup;

    /** Creates new form AutoguidePanel */
    public AutoguidePanel() {
        this(null);
    }

    public AutoguidePanel(XAutoguiderConfig autoguiderConfig) {
        initComponents();
        initComponents2();
        populateComponents2(autoguiderConfig);
    }

    private void initComponents2() {

        buttonGroup = new ButtonGroup();
        buttonGroup.add(jrbAutoguideNo);
        buttonGroup.add(jrbAutoguideYes);
        buttonGroup.add(jrbAutoguideAuto);

        jrbAutoguideNo.setActionCommand(CMD_NO);
        jrbAutoguideYes.setActionCommand(CMD_YES);
        jrbAutoguideAuto.setActionCommand(CMD_AUTO);

    }

    private void populateComponents2(XAutoguiderConfig autoguiderConfig) {

        if (autoguiderConfig == null) {
            setButtons(IAutoguiderConfig.ON_IF_AVAILABLE);
            return;
        }

        int mode = autoguiderConfig.getAutoguiderCommand();
        String name = autoguiderConfig.getAutoguiderName();

        setButtons(mode);
    }

    private void setButtons(int mode) {
        jrbAutoguideYes.getModel().setSelected(mode == IAutoguiderConfig.ON);
        jrbAutoguideNo.getModel().setSelected(mode == IAutoguiderConfig.OFF);
        jrbAutoguideAuto.getModel().setSelected(mode == IAutoguiderConfig.ON_IF_AVAILABLE);
    }

    //return XExecutiveComponent
    public ISequenceComponent getSequenceComponent() {

        IAutoguiderConfig autoguiderConfig = getAutoguiderConfig();
        String name = "UNKNOWN_AUTOGUIDER_COMMAND";
        if (autoguiderConfig.getAutoguiderCommand() == IAutoguiderConfig.OFF) {
            name = "Autoguider_OFF";
        } else if (autoguiderConfig.getAutoguiderCommand() == IAutoguiderConfig.ON) {
            name = "Autoguider_ON";
        } else if (autoguiderConfig.getAutoguiderCommand() == IAutoguiderConfig.ON_IF_AVAILABLE) {
            name = "Autoguider_AUTO";
        }
        return new XExecutiveComponent(name, (IExecutiveAction) autoguiderConfig);
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

    public boolean isValidData() {
        return true;
    }

    private IAutoguiderConfig getAutoguiderConfig() {
        int mode;
        String name;

        String actionCmd = buttonGroup.getSelection().getActionCommand();
        if (actionCmd.equals(CMD_YES)) {
            mode = IAutoguiderConfig.ON;
        } else if (actionCmd.equals(CMD_NO)) {
            mode = IAutoguiderConfig.OFF;
        } else if (actionCmd.equals(CMD_AUTO)) {
            mode = IAutoguiderConfig.ON_IF_AVAILABLE;
        } else {
            return null;
        }
        name = "autoguider1";

        XAutoguiderConfig autoguiderConfig = new XAutoguiderConfig(mode, name);
        return autoguiderConfig;
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jrbAutoguideYes = new javax.swing.JRadioButton();
        jrbAutoguideNo = new javax.swing.JRadioButton();
        jrbAutoguideAuto = new javax.swing.JRadioButton();

        jLabel6.setText("Autoguide");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jrbAutoguideYes.setText("Yes");

        jrbAutoguideNo.setText("Off");

        jrbAutoguideAuto.setText("On if available");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .add(35, 35, 35)
                .add(jrbAutoguideYes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbAutoguideNo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jrbAutoguideAuto)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jrbAutoguideYes)
                    .add(jrbAutoguideNo)
                    .add(jrbAutoguideAuto)
                    .add(jLabel6))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jrbAutoguideAuto;
    private javax.swing.JRadioButton jrbAutoguideNo;
    private javax.swing.JRadioButton jrbAutoguideYes;
    // End of variables declaration//GEN-END:variables

}
