/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RotatorPanel.java
 *
 * Created on Sep 9, 2009, 10:19:07 AM
 */

package ngat.oss.client.gui.panel.sequencepanels;

import ngat.oss.client.gui.panel.*;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import ngat.phase2.IExecutiveAction;
import ngat.phase2.ISequenceComponent;
import ngat.phase2.XBias;
import ngat.phase2.XExecutiveComponent;

/**
 *
 * @author nrc
 */
public class BiasPanel extends javax.swing.JPanel implements SequenceComponentPanel {

    /** Creates new form RotatorPanel */
    public BiasPanel() {
        initComponents();
    }

    public ISequenceComponent getSequenceComponent() {

        //currently assumes that the exposure type is a XMultipleExposure
        XBias bias = new XBias();
        return new XExecutiveComponent("BIAS",(IExecutiveAction) bias);
    }

    public boolean isValidData() {
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();

        jLabel4.setText("Bias");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
            JFrame j = new JFrame();
            j.getContentPane().setLayout(new BorderLayout());
            j.getContentPane().add(new BiasPanel(), BorderLayout.CENTER);
            j.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
