/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstrumentConfigPanel.java
 *
 * Created on Sep 9, 2009, 11:58:53 AM
 */

package ngat.oss.client.gui.panel.sequencepanels;

import ngat.oss.client.gui.panel.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import ngat.oss.client.gui.dialog.NewInstrumentConfigDialog;
import ngat.oss.client.Phase2ModelClient;
import ngat.oss.exception.Phase2Exception;
import ngat.phase2.IExecutiveAction;
import ngat.phase2.IInstrumentConfig;
import ngat.phase2.IInstrumentConfigSelector;
import ngat.phase2.IProgram;
import ngat.phase2.ISequenceComponent;
import ngat.phase2.XExecutiveComponent;
import ngat.phase2.XInstrumentConfigSelector;
import org.apache.log4j.Logger;

/**
 *
 * @author nrc
 */
public class DualBeamSpecInstrumentConfigSelectorPanel extends javax.swing.JPanel implements SequenceComponentPanel {

    static Logger logger = Logger.getLogger(DualBeamSpecInstrumentConfigSelectorPanel.class);

    private ArrayList instrumentConfigList;
    private IProgram program;
    private String instrumentName;
    
    /** Creates new form InstrumentConfigPanel */
    public DualBeamSpecInstrumentConfigSelectorPanel(IProgram program) {
        this.program = program;
        initComponents();
    }

    public DualBeamSpecInstrumentConfigSelectorPanel(String instrumentName, IProgram program) {
        this(program);

        this.instrumentName = instrumentName;
        populateComponents(instrumentName);
    }

    public DualBeamSpecInstrumentConfigSelectorPanel(IInstrumentConfigSelector instrumentConfigSelector, IProgram program) {
        this(program);

        this.instrumentName = instrumentConfigSelector.getInstrumentConfig().getInstrumentName();
        populateComponents(instrumentName);

        selectInstrumentConfig(instrumentConfigSelector.getInstrumentConfig());
    }

    private void populateComponents(String instrumentName) {

        populateInstrumentConfigList(instrumentName);
        selectInstrument(instrumentName);
    }

    //return XExecutiveComponent
    public ISequenceComponent getSequenceComponent() {
        int iConfigIndex = jcbObsInstrumentConfig.getSelectedIndex();
        if (iConfigIndex == -1) {
            return null;
        }
        IInstrumentConfig instrumentConfig = (IInstrumentConfig) instrumentConfigList.get(iConfigIndex);
        IInstrumentConfigSelector instrumentConfigSelector = new XInstrumentConfigSelector(instrumentConfig);
        return new XExecutiveComponent(instrumentConfig.getName(),(IExecutiveAction) instrumentConfigSelector);
    }

    public boolean isValidData() {
        int iConfigIndex = jcbObsInstrumentConfig.getSelectedIndex();
        if (iConfigIndex == -1) {
            return false;
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcbObsInstrumentConfig = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jbtnCreateNewInstrumentConfig = new javax.swing.JButton();
        jlbInstrumentName = new javax.swing.JLabel();

        jLabel10.setText("Instrument:");

        jLabel11.setText("Instrument Config");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("or");

        jbtnCreateNewInstrumentConfig.setText("Create New Instrument Config");
        jbtnCreateNewInstrumentConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateNewInstrumentConfigActionPerformed(evt);
            }
        });

        jlbInstrumentName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel10)
                        .add(18, 18, 18)
                        .add(jlbInstrumentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jcbObsInstrumentConfig, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 159, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel12)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnCreateNewInstrumentConfig)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jlbInstrumentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jbtnCreateNewInstrumentConfig)
                    .add(jLabel11)
                    .add(jcbObsInstrumentConfig, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectInstrument(String instrumentName) {
        jlbInstrumentName.setText(instrumentName);
    }

    private void selectInstrumentConfig(IInstrumentConfig instrumentConfig) {

        //select the given instrument config in the gui
        //instrumentConfigList has been populated by populateInstrumentConfigList([String])
        Iterator i = instrumentConfigList.iterator();
        while (i.hasNext()) {
            IInstrumentConfig foundConfig = (IInstrumentConfig) i.next();
            if (foundConfig.getName().equals(instrumentConfig.getName())) {
                jcbObsInstrumentConfig.setSelectedItem(foundConfig.getName());
            }
        }
    }

    //populate instrumentConfigList and jcbObsInstrumentConfig object with all instr cfgs of programme
    private void populateInstrumentConfigList() throws Phase2Exception {
        jcbObsInstrumentConfig.removeAllItems();
        instrumentConfigList = new ArrayList();
        instrumentConfigList = (ArrayList) Phase2ModelClient.getInstance().listInstrumentConfigs(program.getID());
        Iterator ici = instrumentConfigList.iterator();
        while (ici.hasNext()) {
            IInstrumentConfig instrumentConfig = (IInstrumentConfig) ici.next();
            jcbObsInstrumentConfig.addItem(instrumentConfig.getName());
        }
    }

    //populate instrumentConfigList and jcbObsInstrumentConfig object with all instr cfgs of programme that are relevant to instrument: instrumentName
    private void populateInstrumentConfigList(String instrumentName) {
        jcbObsInstrumentConfig.removeAllItems();
        instrumentConfigList = new ArrayList();
        try {
            List allInstrumentConfigList = Phase2ModelClient.getInstance().listInstrumentConfigs(program.getID());
            Iterator ici = allInstrumentConfigList.iterator();
            while (ici.hasNext()) {
                IInstrumentConfig instrumentConfig = (IInstrumentConfig) ici.next();
                if (instrumentConfig.getInstrumentName() != null) {
                    if (instrumentConfig.getInstrumentName().equalsIgnoreCase(instrumentName)) {
                        jcbObsInstrumentConfig.addItem(instrumentConfig.getName());
                        instrumentConfigList.add(instrumentConfig);
                    }
                }
            }
        } catch (Phase2Exception ex) {
            ex.printStackTrace();
            logger.error(ex);
        }
    }
    
    private void jbtnCreateNewInstrumentConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateNewInstrumentConfigActionPerformed

        NewInstrumentConfigDialog dialog = new NewInstrumentConfigDialog(true, instrumentName);
        dialog.setVisible(true);

        //blocks

        IInstrumentConfig instrumentConfig = dialog.getInstrumentConfig();
        dialog.setVisible(false);
        dialog.dispose();

        if (instrumentConfig == null) {
            return;
        }
        if (dialog.wasKilled()) {
            return;
        }
        try {
            Phase2ModelClient.getInstance().addInstrumentConfig(program.getID(), instrumentConfig);
            //populate instrument config list dependent upon selected instrument name
            populateInstrumentConfigList(instrumentName);
            //select new instrument config in combo box
            String instrCfgName = instrumentConfig.getName();
            jcbObsInstrumentConfig.setSelectedItem(instrCfgName);
        } catch (Phase2Exception ex) {
            ex.printStackTrace();
            logger.error(ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
}//GEN-LAST:event_jbtnCreateNewInstrumentConfigActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JButton jbtnCreateNewInstrumentConfig;
    private javax.swing.JComboBox jcbObsInstrumentConfig;
    private javax.swing.JLabel jlbInstrumentName;
    // End of variables declaration//GEN-END:variables

}
