/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefocusPanel.java
 *
 * Created on Sep 9, 2009, 11:04:38 AM
 */

package ngat.oss.client.gui.panel.sequencepanels;

import ngat.oss.client.gui.panel.*;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import ngat.phase2.IExecutiveAction;
import ngat.phase2.ISequenceComponent;
import ngat.phase2.XExecutiveComponent;
import ngat.phase2.XPositionOffset;
import ngat.phase2.util.UnitConverter;

/**
 *
 * @author nrc
 */
public class PositionOffsetPanel extends javax.swing.JPanel implements SequenceComponentPanel {

    private static final String NON_CUMULATIVE = "NON_CUMULATIVE";
    private static final String CUMULATIVE = "CUMULATIVE";

    ButtonGroup buttonGroup = new ButtonGroup();

    /** Creates new form DefocusPanel */
    public PositionOffsetPanel() {
        this(null);
        
       
        setButtons(false);
    }

    public PositionOffsetPanel(XPositionOffset positionOffset) {
        initComponents();
        initComponents2();

        if (positionOffset == null) {
            setButtons(true);
            jtfDecOffset.setText("0.0");
            jtfRAOffset.setText("0.0");
            return;
        }

        boolean isRelative = positionOffset.isRelative();
        setButtons(isRelative);

        double decOffsetRads = positionOffset.getDecOffset();
        double raOffsetRads = positionOffset.getRAOffset();

        double raOffsetArcsecs = UnitConverter.convertRadsToArcSecs(raOffsetRads);
        double decOffsetArcsecs = UnitConverter.convertRadsToArcSecs(decOffsetRads);

        jtfDecOffset.setText(String.valueOf(decOffsetArcsecs));
        jtfRAOffset.setText(String.valueOf(raOffsetArcsecs));
    }

    private void initComponents2() {
        jrbCumulative.getModel().setActionCommand(CUMULATIVE);
        jrbNoncumulative.getModel().setActionCommand(NON_CUMULATIVE);

        buttonGroup = new ButtonGroup();
        buttonGroup.add(jrbNoncumulative);
        buttonGroup.add(jrbCumulative);
    }

    private void setButtons(boolean cumulative) {
        jrbCumulative.getModel().setSelected(cumulative);
        jrbNoncumulative.getModel().setSelected(!cumulative);
    }

    //return XExecutiveComponent
    public ISequenceComponent getSequenceComponent() {
        
        boolean relative = buttonGroup.getSelection().getActionCommand().equals(CUMULATIVE);
        String name = "UNKNOWN_OFFSET_TYPE";
        if (relative) {
            name = "CUMULATIVE_POSITION_OFFSET";
        } else {
            name = "NON_CUMULATIVE_POSITION_OFFSET";
        }
        double raOffsetArcsecs = Double.parseDouble(jtfRAOffset.getText());
        double decOffsetArcsecs = Double.parseDouble(jtfDecOffset.getText());

        double raOffsetRads = Math.toRadians(raOffsetArcsecs / 3600);
        double decOffsetRads = Math.toRadians(decOffsetArcsecs / 3600);

        XPositionOffset positionOffset = new XPositionOffset(relative, raOffsetRads, decOffsetRads);


        return new XExecutiveComponent(name,(IExecutiveAction) positionOffset);
    }

    public boolean isValidData() {
        try {
            double offset = Double.parseDouble(jtfRAOffset.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric value for RA offset");
            return false;
        }

        try {
            double offset = Double.parseDouble(jtfDecOffset.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric value for DEC offset");
            return false;
        }
       
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jtfRAOffset = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jrbNoncumulative = new javax.swing.JRadioButton();
        jrbCumulative = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jtfDecOffset = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpHelpPane = new javax.swing.JTextPane();

        jLabel9.setText("RA Offset:");

        jtfRAOffset.setText("0.0");
        jtfRAOffset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRAOffsetActionPerformed(evt);
            }
        });

        jLabel10.setText("arcsecs");

        jrbNoncumulative.setText("Non-cumulative");

        jrbCumulative.setText("Cumulative");

        jLabel11.setText("DEC Offset:");

        jtfDecOffset.setText("0.0");

        jLabel12.setText("arcsecs");

        jLabel13.setText("Position offset");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtpHelpPane.setEditable(false);
        jtpHelpPane.setText("Note that you cannot offset whilst autoguiding.");
        jScrollPane1.setViewportView(jtpHelpPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jLabel11)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jtfDecOffset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jrbNoncumulative))
                                .add(12, 12, 12)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel10)
                                    .add(jLabel12)))
                            .add(layout.createSequentialGroup()
                                .add(jLabel9)
                                .add(18, 18, 18)
                                .add(jtfRAOffset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jrbCumulative)))
                    .add(jLabel13))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel9)
                            .add(jtfRAOffset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel11)
                            .add(jtfDecOffset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jrbNoncumulative)
                        .add(5, 5, 5)
                        .add(jrbCumulative))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLabel10)
                        .add(20, 20, 20)
                        .add(jLabel12)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRAOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRAOffsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRAOffsetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbCumulative;
    private javax.swing.JRadioButton jrbNoncumulative;
    private javax.swing.JTextField jtfDecOffset;
    private javax.swing.JTextField jtfRAOffset;
    private javax.swing.JTextPane jtpHelpPane;
    // End of variables declaration//GEN-END:variables

}
