/*
 * CreateObservationSequenceFrame.java
 *
 * Created on June 11, 2009, 10:35 AM
 */

package ngat.oss.client.gui.frame;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ngat.oss.client.Phase2ModelClient;
import ngat.oss.client.gui.panel.ObservationSequenceEditorPanel;
import ngat.oss.client.gui.panel.ShowObservationSequencePanel;
import ngat.oss.client.gui.listeners.ObservationSequenceAddedListener;
import ngat.oss.client.gui.reference.CONST;
import ngat.oss.exception.Phase2Exception;
import ngat.phase2.IGroup;
import ngat.phase2.IProgram;
import ngat.phase2.ISequenceComponent;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class EditObservationSequenceFrame extends javax.swing.JFrame {

    static Logger logger = Logger.getLogger(EditObservationSequenceFrame.class);

    private IGroup group;
    private IProgram program;
    private ArrayList observationSequenceAddedListeners = new ArrayList();

    /** Creates new form CreateObservationSequenceFrame */
    public EditObservationSequenceFrame(IGroup group) throws Phase2Exception {
        this.group = group;
        this.program = getProgrammeOfGroup(group); //throws Exception
        
        initComponents();

        this.setTitle("Editing Observation Sequence of Group: " + group.getName());
        
        jpContainerPanel.setLayout(new BorderLayout());
        showHeaderPanel(new ObservationSequenceEditorPanel(group, program, false));
        setSize(CONST.MAIN_FRAME_SIZE);

        centerFrame();
    }
    
    public void showHeaderPanel(final JPanel displayPanel) {
        
        final JPanel containerPanel = jpContainerPanel;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                containerPanel.removeAll();
                containerPanel.add(displayPanel, BorderLayout.CENTER);
                containerPanel.validate();
                containerPanel.repaint();
            }
        });
    }

    private IProgram getProgrammeOfGroup(IGroup group) throws Phase2Exception {
        IProgram programme = Phase2ModelClient.getInstance().getProgrammeOfGroup(group.getID());
        return programme;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnForward = new javax.swing.JButton();
        jpContainerPanel = new javax.swing.JPanel();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtnForward.setText("Continue");
        jbtnForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnForwardActionPerformed(evt);
            }
        });

        jpContainerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.layout.GroupLayout jpContainerPanelLayout = new org.jdesktop.layout.GroupLayout(jpContainerPanel);
        jpContainerPanel.setLayout(jpContainerPanelLayout);
        jpContainerPanelLayout.setHorizontalGroup(
            jpContainerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 812, Short.MAX_VALUE)
        );
        jpContainerPanelLayout.setVerticalGroup(
            jpContainerPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 627, Short.MAX_VALUE)
        );

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jbtnForward)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 606, Short.MAX_VALUE)
                .add(jbtnCancel)
                .addContainerGap())
            .add(jpContainerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(new java.awt.Component[] {jbtnCancel, jbtnForward}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jpContainerPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnForward)
                    .add(jbtnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbtnForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnForwardActionPerformed

    //System.err.println(this.getSize());
    
    Component containedComponent = jpContainerPanel.getComponents()[0];
    
    if (containedComponent instanceof ObservationSequenceEditorPanel) {
        ObservationSequenceEditorPanel photomSequenceEditorPanel = (ObservationSequenceEditorPanel) containedComponent;
        String errorMessage = photomSequenceEditorPanel.validateObservationSequence();
        if (errorMessage != null) {
            JOptionPane.showMessageDialog(this, errorMessage);
            return;
        }
        ISequenceComponent observationSequence = photomSequenceEditorPanel.getObservationSequence();
        if (observationSequence != null) {
            try {
                logger.info("invoking Phase2ModelClient.getInstance().updateObservationSequenceOfGroup(" + group.getID() + ", " + observationSequence + ")");
                
                Phase2ModelClient.getInstance().updateObservationSequenceOfGroup(group.getID(), observationSequence, 999);
                sendObservationSequenceAddedEvent();
                JOptionPane.showMessageDialog(this, "Observation sequence altered");
                showHeaderPanel(new ShowObservationSequencePanel(group));
                jbtnCancel.setVisible(false);
            } catch (RemoteException ex) {
                ex.printStackTrace();
                logger.error(ex);
                JOptionPane.showMessageDialog(this, ex);
                this.dispose();
                this.setVisible(false);
                return;
            }
        } else {
            //observationSequence == null, leave the panel in place
            return;
        }
    }  else if (containedComponent instanceof ShowObservationSequencePanel) {
        this.setVisible(false);
        this.dispose();
    }
}//GEN-LAST:event_jbtnForwardActionPerformed

private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
    
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_jbtnCancelActionPerformed

public void addObservationSequenceAddedListener(ObservationSequenceAddedListener obsSeqAddedListener) {
    observationSequenceAddedListeners.add(obsSeqAddedListener);
}

//send to listening components an event indicating that a sequence has been added
private void sendObservationSequenceAddedEvent() {
    Iterator i = observationSequenceAddedListeners.iterator();
    while (i.hasNext()) {
        ObservationSequenceAddedListener observationSequenceAddedListener
                = (ObservationSequenceAddedListener)i.next();
        System.out.println(observationSequenceAddedListener);
        observationSequenceAddedListener.receiveObservationSequenceAdded();
    }
}

    private void centerFrame() {
        Dimension screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        double hd = screenDimension.getHeight();
        double wd = screenDimension.getWidth();

        double yd = (hd - this.getBounds().getHeight()) / 2;
        double xd = (wd - this.getBounds().getWidth()) / 2;

        final int x = (int) xd;
        final int y = (int) yd;

        EventQueue.invokeLater(
                new Runnable() {

                    public void run() {
                        EditObservationSequenceFrame.this.setLocation(x, y);
                    }
                });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnForward;
    private javax.swing.JPanel jpContainerPanel;
    // End of variables declaration//GEN-END:variables

}
