/*
 * Created on April 17, 2009, 2:07 PM
 */

package ngat.oss.client.gui.panel.timingConstraint;

import ngat.oss.client.gui.panel.interfaces.ITimingConstraintPanel;
import ngat.phase2.ITimingConstraint;
import ngat.phase2.XFlexibleTimingConstraint;

/**
 *
 * @author  nrc
 */
public class FlexibleTimingConstraintEditorPanel extends javax.swing.JPanel implements ITimingConstraintPanel {

    private XFlexibleTimingConstraint flexibleTimingConstraint;
    private boolean enabled;
    private boolean isNewTimingConstraint;

    /** Creates new form  */
    public FlexibleTimingConstraintEditorPanel(XFlexibleTimingConstraint flexibleTimingConstraint, boolean isNewTimingConstraint) {
        this.flexibleTimingConstraint = flexibleTimingConstraint;
        this.isNewTimingConstraint = isNewTimingConstraint;
        
        initComponents();
        populateComponents();
    }

    private void populateComponents() {
        dteActivationDate.setTime(flexibleTimingConstraint.getActivationDate(), isNewTimingConstraint);
        dteExpiryDate.setTime(flexibleTimingConstraint.getExpiryDate(), isNewTimingConstraint);
    }
    
    public ITimingConstraint getTimingConstraint() {

        try {
            long activationDate = dteActivationDate.getTime();
            long expiryDate = dteExpiryDate.getTime();

            flexibleTimingConstraint.setActivationDate(activationDate);
            flexibleTimingConstraint.setExpiryDate(expiryDate);

            return flexibleTimingConstraint;
        } catch (Exception e) {
            return null;
        }
    }
    
    public boolean containsValidTimingConstraint() {
        try {
            long activationDate = dteActivationDate.getTime();
            long expiryDate = dteExpiryDate.getTime();

            flexibleTimingConstraint.setActivationDate(activationDate);
            flexibleTimingConstraint.setExpiryDate(expiryDate);

            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
        
        dteActivationDate.setEnabled(enabled);
        dteExpiryDate.setEnabled(enabled);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dteActivationDate = new ngat.beans.guibeans.DateTimeEditorPanel();
        dteExpiryDate = new ngat.beans.guibeans.DateTimeEditorPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        dteActivationDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Activation Date (YYYY/MM/DD HH:MM:SS)"));
        dteActivationDate.setTitle("Activation Date");

        dteExpiryDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Expiry Date (YYYY/MM/DD HH:MM:SS)"));
        dteExpiryDate.setTitle("Expiry Date");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 12));
        jLabel1.setText("Flexible Timing Constraint");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(dteActivationDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .add(dteExpiryDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dteActivationDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dteExpiryDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ngat.beans.guibeans.DateTimeEditorPanel dteActivationDate;
    private ngat.beans.guibeans.DateTimeEditorPanel dteExpiryDate;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
