/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicDetectorConfigPanel.java
 *
 * Created on Oct 26, 2010, 10:40:41 AM
 */

package ngat.beans.guibeans;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import ngat.phase2.IDetectorConfig;
import ngat.phase2.XDetectorConfig;
import ngat.phase2.XWindow;

/**
 *
 * @author nrc
 */
public class DetectorConfigAdvancedPanel extends javax.swing.JPanel implements DetectorConfigPanel {

    /** Creates new form BasicDetectorConfigPanel */
    public DetectorConfigAdvancedPanel() {
        initComponents();
    }

    public DetectorConfigAdvancedPanel(IDetectorConfig detectorConfig) {
        initComponents();
        setDetectorConfig(detectorConfig);
    }

    public boolean containsValidDetectorConfig() {
        if (!windowPanel.containsValidWindow()) {
            return false;
        }

        try {
            Integer.parseInt(jtfXBin.getText());
            Integer.parseInt(jtfYBin.getText());
        } catch (NumberFormatException nfe) {
            return false;
        }

        return true;
    }

    public void setDetectorConfig(IDetectorConfig detectorConfig) {

        int xBin = detectorConfig.getXBin();
        int yBin = detectorConfig.getYBin();

        jtfXBin.setText(String.valueOf(xBin));
        jtfYBin.setText(String.valueOf(yBin));

        List windows = detectorConfig.listWindows();
        Iterator wi = windows.iterator();
        while (wi.hasNext()){
            XWindow window = (XWindow) wi.next();
            windowPanel.setWindow(window);
        }

    }

    public IDetectorConfig getDetectorConfig() {

        XDetectorConfig detectorConfig = new  XDetectorConfig();
        int xBin = Integer.parseInt(jtfXBin.getText());
        int yBin = Integer.parseInt(jtfYBin.getText());
        detectorConfig.setXBin(xBin);
        detectorConfig.setYBin(yBin);

        //numOfAllowedWindows == 1 (not implemented more atm)
        List windowsList = new ArrayList();
        windowsList.add(windowPanel.getWindow());
        detectorConfig.setWindows(windowsList);

        return detectorConfig;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfXBin = new javax.swing.JTextField();
        jtfYBin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        windowPanel = new ngat.beans.guibeans.WindowPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detector Config"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Binning"));

        jLabel1.setText("x");

        jLabel7.setText("y");

        jtfXBin.setText("0000");

        jtfYBin.setText("0000");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jtfXBin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jtfYBin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(16, 16, 16)
                                .add(jLabel7))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(jLabel1)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                .add(jPanel1Layout.createSequentialGroup()
                    .add(jLabel1)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jtfXBin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createSequentialGroup()
                    .add(jLabel7)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(jtfYBin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel5.setText("All values in non-binned pixels");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(windowPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel5)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(windowPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfXBin;
    private javax.swing.JTextField jtfYBin;
    private ngat.beans.guibeans.WindowPanel windowPanel;
    // End of variables declaration//GEN-END:variables


}
