/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BasicDetectorConfigPanel.java
 *
 * Created on Oct 26, 2010, 10:40:41 AM
 */

package ngat.beans.guibeans;

import javax.swing.JOptionPane;
import ngat.oss.client.gui.reference.CONST;
import ngat.phase2.IDetectorConfig;
import ngat.phase2.XDetectorConfig;

/**
 *
 * @author nrc
 */
public class DetectorConfigStandardPanel extends javax.swing.JPanel implements DetectorConfigPanel {

    /** Creates new form BasicDetectorConfigPanel */
    public DetectorConfigStandardPanel() {
        this(null);
    }

    public DetectorConfigStandardPanel(IDetectorConfig detectorConfig) {
        initComponents();
        setDetectorConfig(detectorConfig);
    }
    
    public void setDetectorConfig(IDetectorConfig detectorConfig) {
        
        //JOptionPane.showMessageDialog(this, "setDetectorConfig(" + detectorConfig + ")");
        
        if (detectorConfig != null) {
            
            if (detectorConfig.getXBin() == 1) {
                jcbBin.setSelectedItem(CONST.BIN_1);
            } else if (detectorConfig.getXBin() == 2) {
                jcbBin.setSelectedItem(CONST.BIN_2);
            } else if (detectorConfig.getXBin() == 4) {
                jcbBin.setSelectedItem(CONST.BIN_4);
            }
        }

    }


    public boolean containsValidDetectorConfig() {
        return true;
    }
    
    public IDetectorConfig getDetectorConfig() {

        XDetectorConfig detectorConfig = new  XDetectorConfig();
        String binString = (String) jcbBin.getSelectedItem();
        int xBin = 0, yBin = 0;
        if (binString.equalsIgnoreCase(CONST.BIN_1)) {
            xBin = 1;
            yBin = 1;
        } else if (binString.equalsIgnoreCase(CONST.BIN_2)) {
            xBin = 2;
            yBin = 2;
        } else if (binString.equalsIgnoreCase(CONST.BIN_4)) {
            xBin = 4;
            yBin = 4;
        }

        detectorConfig.setXBin(xBin);
        detectorConfig.setYBin(yBin);
        detectorConfig.setWindows(null);

        return detectorConfig;
    }

    public void setBinningOptions(String[] binningOptions) {

        jcbBin.setModel(new javax.swing.DefaultComboBoxModel(binningOptions));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbBin = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detector Config"));

        jcbBin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { CONST.BIN_1,CONST.BIN_2 }));

        jLabel3.setText("Binning:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcbBin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jcbBin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox jcbBin;
    // End of variables declaration//GEN-END:variables

}
