/*
 * DecSpinner.java
 *
 * Created on 14 December 2007, 11:11
 */
package ngat.beans.guibeans;

import java.text.ParseException;
import javax.swing.border.TitledBorder;

/**
 *
 * @author  nrc
 */
public class NumberEditorPanel extends javax.swing.JPanel {

    private boolean enabled;
    private double number;

    /** Creates new form DecSpinner */
    public NumberEditorPanel() {
        initComponents();
    }

    public double getNumber() throws NumberFormatException {
        return Double.parseDouble(jtfNumber.getText());
    }

    public void setNumber(double number) {
        this.number = number;
        jtfNumber.setText(String.valueOf(number));
    }
    
    public void setTitle(String title) {
        TitledBorder titledBorder = (TitledBorder)this.getBorder();
        titledBorder.setTitle(title);
    }
    
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
        
        jtfNumber.setEnabled(enabled);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jtfNumber = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "title", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(155, 95));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));

        jtfNumber.setColumns(1);
        jtfNumber.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jtfNumber.setText(" ");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .add(jLabel5))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jtfNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jtfNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(jLabel5))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jtfNumber;
    // End of variables declaration//GEN-END:variables
    
}
