/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WindowPanel.java
 *
 * Created on Oct 19, 2010, 12:39:14 PM
 */

package ngat.beans.guibeans;

import ngat.oss.client.gui.util.LimitedCharactersDocument;
import ngat.phase2.XWindow;

/**
 *
 * @author nrc
 */
public class WindowPanel extends javax.swing.JPanel {

    /** Creates new form WindowPanel */
    public WindowPanel() {
        initComponents();
        setUpComponents();
    }

    public WindowPanel(XWindow window) {
        initComponents();
        setUpComponents();
        setWindow(window);
    }

    public void setWindow(XWindow window) {
        jtfX.setText(String.valueOf(window.getX()));
        jtfY.setText(String.valueOf(window.getY()));
        jtfW.setText(String.valueOf(window.getWidth()));
        jtfH.setText(String.valueOf(window.getHeight()));
    }

    public XWindow getWindow() {
        int x, y, w, h;
        x = Integer.parseInt(jtfX.getText());
        y = Integer.parseInt(jtfY.getText());
        w = Integer.parseInt(jtfW.getText());
        h = Integer.parseInt(jtfH.getText());

        XWindow window = new XWindow(x,y,w,h);
        return window;
    }

    public boolean containsValidWindow() {
        try {
            Integer.parseInt(jtfX.getText());
            Integer.parseInt(jtfY.getText());
            Integer.parseInt(jtfW.getText());
            Integer.parseInt(jtfH.getText());
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }

    private void setUpComponents() {
        jtfX.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.NUMBERS_ONLY_LIMITATION));
        jtfY.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.NUMBERS_ONLY_LIMITATION));
        jtfW.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.NUMBERS_ONLY_LIMITATION));
        jtfH.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.NUMBERS_ONLY_LIMITATION));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfY = new javax.swing.JTextField();
        jtfW = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Window"));

        jLabel1.setText("x");

        jtfX.setText("0");

        jLabel2.setText("y");

        jtfY.setText("0");

        jtfW.setText("0");

        jLabel3.setText("w");

        jtfH.setText("0");

        jLabel4.setText("h");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(54, 54, 54)
                .add(jLabel2)
                .add(55, 55, 55)
                .add(jLabel3)
                .add(52, 52, 52)
                .add(jLabel4))
            .add(layout.createSequentialGroup()
                .add(jtfX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtfH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 52, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel3)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1))
                .add(2, 2, 2)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jtfH, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfW, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtfH;
    private javax.swing.JTextField jtfW;
    private javax.swing.JTextField jtfX;
    private javax.swing.JTextField jtfY;
    // End of variables declaration//GEN-END:variables

}
