package ngat.oss.client.gui.panel.instrumentConfig;

import ngat.oss.client.gui.panel.interfaces.IInstrumentConfigPanel;
import javax.swing.JOptionPane;
import ngat.oss.client.gui.reference.CONST;
import ngat.phase2.IInstrumentConfig;
import ngat.phase2.XDetectorConfig;
import ngat.phase2.XDualBeamSpectrographInstrumentConfig;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class DualBeamSpectrographInstrumentConfigEditorPanel extends javax.swing.JPanel implements IInstrumentConfigPanel {

    static Logger logger = Logger.getLogger(DualBeamSpectrographInstrumentConfigEditorPanel.class);

    private boolean enabled;
    private XDualBeamSpectrographInstrumentConfig originalImagerInstrumentConfig;
    
    public DualBeamSpectrographInstrumentConfigEditorPanel(XDualBeamSpectrographInstrumentConfig dualBeamSpecInstrumentConfig, boolean canChangeInstrument) {
        this.originalImagerInstrumentConfig = dualBeamSpecInstrumentConfig;
        initComponents();
        populateComponents(dualBeamSpecInstrumentConfig,  canChangeInstrument );
    }

    private void populateComponents(XDualBeamSpectrographInstrumentConfig dualBeamSpecInstrumentConfig, boolean canChangeInstrument) {
        
        if (dualBeamSpecInstrumentConfig == null) {
            return;
        }
        
        String instrumentName = dualBeamSpecInstrumentConfig.getInstrumentName();
        jcbInstrumentName.setSelectedItem(instrumentName);

        jcbInstrumentName.setEnabled(canChangeInstrument);

        try {
            jtfInstrumentConfigName.setText(dualBeamSpecInstrumentConfig.getName());
        } catch (Exception e) {
            e.printStackTrace();
            logger.error(e);
            JOptionPane.showMessageDialog(this, e);
        }

        int resolution = dualBeamSpecInstrumentConfig.getResolution();
        switch (resolution) {
            case XDualBeamSpectrographInstrumentConfig.LOW_RESOLUTION:
                jcbResolution.setSelectedIndex(0);
                break;
            case XDualBeamSpectrographInstrumentConfig.HIGH_RESOLUTION:
                jcbResolution.setSelectedIndex(1);
                break;
        }


    }
    
    public IInstrumentConfig getInstrumentConfig() throws Exception {
        
        XDualBeamSpectrographInstrumentConfig dualBeamSpectrographInstrumentConfig = new XDualBeamSpectrographInstrumentConfig();
            String name;
            String instrumentName;
            //detector config with a binning of 1 atm.
            XDetectorConfig detectorConfig = new  XDetectorConfig();
                detectorConfig.setXBin(1);
                detectorConfig.setYBin(1);

        dualBeamSpectrographInstrumentConfig.setID(originalImagerInstrumentConfig.getID());
        name = jtfInstrumentConfigName.getText();
        instrumentName = (String)jcbInstrumentName.getSelectedItem();

        int resolution = 0;
        if (jcbResolution.getSelectedItem().equals("LOW_RESOLUTION")) {
            resolution = XDualBeamSpectrographInstrumentConfig.LOW_RESOLUTION;
        } else {
            resolution = XDualBeamSpectrographInstrumentConfig.HIGH_RESOLUTION;
        }

        dualBeamSpectrographInstrumentConfig.setResolution(resolution);

        dualBeamSpectrographInstrumentConfig.setDetectorConfig(detectorConfig);
        dualBeamSpectrographInstrumentConfig.setName(name);
        dualBeamSpectrographInstrumentConfig.setInstrumentName(instrumentName);
       
        return dualBeamSpectrographInstrumentConfig;
    }
    
    public boolean containsValidInstrumentConfig() {
        if (jtfInstrumentConfigName.getText().trim().length() ==0) {
            return false;
        }

        return true;
    }
    
    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;

        jcbInstrumentName.setEnabled(enabled);
        jbtnRemoveFilter.setEnabled(enabled);
        jtfInstrumentConfigName.setEnabled(enabled);
    }
                
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jcbInstrumentName = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jtfInstrumentConfigName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbtnRemoveFilter = new javax.swing.JButton();
        jpFilterWheel1 = new javax.swing.JPanel();
        jcbResolution = new javax.swing.JComboBox();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Instrument Name"));

        jcbInstrumentName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { CONST.FRODO_RED, CONST.FRODO_BLUE }));
        jcbInstrumentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbInstrumentNameActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jcbInstrumentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jcbInstrumentName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Instrument Config Name"));

        jLabel3.setText("(no spaces please)");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jtfInstrumentConfigName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .add(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jtfInstrumentConfigName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resolution Specification"));

        jbtnRemoveFilter.setText(">");
        jbtnRemoveFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveFilterActionPerformed(evt);
            }
        });

        jcbResolution.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LOW_RESOLUTION", "HIGH_RESOLUTION" }));

        org.jdesktop.layout.GroupLayout jpFilterWheel1Layout = new org.jdesktop.layout.GroupLayout(jpFilterWheel1);
        jpFilterWheel1.setLayout(jpFilterWheel1Layout);
        jpFilterWheel1Layout.setHorizontalGroup(
            jpFilterWheel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpFilterWheel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jcbResolution, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpFilterWheel1Layout.setVerticalGroup(
            jpFilterWheel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jcbResolution, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jpFilterWheel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(267, 267, 267)
                .add(jbtnRemoveFilter, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jbtnRemoveFilter)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(jpFilterWheel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtnRemoveFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveFilterActionPerformed

}//GEN-LAST:event_jbtnRemoveFilterActionPerformed

private void jcbInstrumentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbInstrumentNameActionPerformed
    String selectedInstrumentName = (String)jcbInstrumentName.getSelectedItem();
    if (selectedInstrumentName == null) {
        return;
    }
}//GEN-LAST:event_jcbInstrumentNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtnRemoveFilter;
    private javax.swing.JComboBox jcbInstrumentName;
    private javax.swing.JComboBox jcbResolution;
    private javax.swing.JPanel jpFilterWheel1;
    private javax.swing.JTextField jtfInstrumentConfigName;
    // End of variables declaration//GEN-END:variables

}
