/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MultipleExposurePanel.java
 *
 * Created on Sep 29, 2010, 11:15:04 AM
 */

package ngat.oss.client.gui.panel.sequencepanels.sub;

import javax.swing.JOptionPane;
import ngat.oss.client.gui.reference.Session;
import ngat.phase2.IExposure;
import ngat.phase2.XMultipleExposure;

/**
 *
 * @author nrc
 */
public class MultipleExposurePanel extends javax.swing.JPanel implements IExposurePanel {

    XMultipleExposure multipleExposure;

    /** Creates new form MultipleExposurePanel */
    public MultipleExposurePanel(XMultipleExposure multipleExposure) {
        initComponents();
        this.multipleExposure = multipleExposure;
        populateComponents();
    }

    private void populateComponents() {
        boolean isStandard = multipleExposure.isStandard();
        int repeatCount = multipleExposure.getRepeatCount();
        double exposureTime = multipleExposure.getExposureTime();

        if (Session.getInstance().getUser().isSuperUser()) {
            jcbIsStandard.setEnabled(true);
            jcbIsStandard.setSelected(isStandard);
        } else {
            jcbIsStandard.setEnabled(false);
        }

        jcbIsStandard.setSelected(isStandard);
        jtfExposureCount.setText(String.valueOf(repeatCount));
        jtfExposureTime.setText(String.valueOf(exposureTime / 1000));
    }

    public IExposure getExposure() {

        XMultipleExposure multipleExposure = new XMultipleExposure();
        double exposureTime = Double.parseDouble(jtfExposureTime.getText());
        int repeatCount = Integer.parseInt(jtfExposureCount.getText());

        boolean isStandard;
        if (Session.getInstance().getUser().isSuperUser()) {
            //use the ui to get the value
            isStandard = jcbIsStandard.isSelected();
        } else {
            //set it to what it was before
            isStandard = multipleExposure.isStandard();
        }
        
        multipleExposure.setExposureTime(exposureTime * 1000); //convert to mS
        multipleExposure.setRepeatCount(repeatCount);
        multipleExposure.setStandard(isStandard);

        return multipleExposure;
    }

    public boolean containsValidData() {
        try {
            Double.parseDouble(jtfExposureTime.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric value for exposure time");
            return false;
        }

        try {
            Integer.parseInt(jtfExposureCount.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a numeric value for the repeat count");
            return false;
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfExposureTime = new javax.swing.JTextField();
        lblRepeats = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtfExposureCount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jcbIsStandard = new javax.swing.JCheckBox();

        jtfExposureTime.setText("1.0");

        lblRepeats.setText("repeats:");

        jLabel16.setText("exposure time:");

        jtfExposureCount.setText("1");

        jLabel14.setText("seconds");

        jcbIsStandard.setText("is standard");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(lblRepeats)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jtfExposureCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jtfExposureTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 51, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(jcbIsStandard))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtfExposureCount, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblRepeats)
                    .add(jcbIsStandard))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel14)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jtfExposureTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel16)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JCheckBox jcbIsStandard;
    private javax.swing.JTextField jtfExposureCount;
    private javax.swing.JTextField jtfExposureTime;
    private javax.swing.JLabel lblRepeats;
    // End of variables declaration//GEN-END:variables



}
