/*
 * ProgrammeHeaderPanel.java
 *
 * Created on March 27, 2009, 2:54 PM
 */
package ngat.oss.client.gui.panel.headers;

import ngat.oss.client.gui.panel.interfaces.IEditablePanel;
import javax.swing.JOptionPane;
import ngat.oss.client.Phase2ModelClient;
import ngat.oss.client.gui.dialog.InstrumentConfigListDialog;
import ngat.oss.client.gui.dialog.TargetListDialog;
import ngat.oss.client.gui.frame.MainFrame;
import ngat.oss.client.gui.reference.Session;
import ngat.oss.client.gui.util.LimitedCharactersDocument;
import ngat.oss.exception.Phase2Exception;
import ngat.phase2.IProgram;
import ngat.phase2.XProgram;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class ProgrammeHeaderPanel extends javax.swing.JPanel implements IEditablePanel {

    static Logger logger = Logger.getLogger(ProgrammeHeaderPanel.class);

    private IProgram program;
    private boolean enabled;

    /** Creates new form ProgrammeHeaderPanel */
    public ProgrammeHeaderPanel(IProgram program) {
        this.program = program;
        initComponents();
        try {
            populateComponents();
        } catch (Exception ex) {
            ex.printStackTrace();
            logger.error(ex);
        }
        setEnabled(false);

        //hide the edit and submit buttons if they aren't a SU
        boolean isSuperUser = Session.getInstance().getUser().isSuperUser();
        jbtnEdit.setVisible(isSuperUser);
        jbtnSubmit.setVisible(isSuperUser);
    }

    private void populateComponents() throws Exception {
        jtfName.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.STRICT_LIMITATION));
        
        jtfName.setText(program.getName());
        jtfDescription.setText(program.getDescription());
    }

    public boolean isBeingEdited() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {

        jtfDescription.setEnabled(enabled);
        jtfName.setEnabled(enabled);
        
        jbtnEdit.setEnabled(!enabled);
        jbtnSubmit.setEnabled(enabled);
        jbtnCancel.setEnabled(enabled);
        
        this.enabled = enabled;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDescription = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnSubmit = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnTargets = new javax.swing.JButton();
        jbtnInstrCfgs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpHelpPane = new javax.swing.JTextPane();
        jbtnCancel = new javax.swing.JButton();

        jtfName.setFont(new java.awt.Font("Lucida Grande", 0, 10));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel3.setText("Description");

        jtfDescription.setFont(new java.awt.Font("Lucida Grande", 0, 10));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 10));
        jLabel1.setText("PROGRAMME");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("Name");

        jbtnSubmit.setForeground(new java.awt.Color(255, 0, 0));
        jbtnSubmit.setText("Submit");
        jbtnSubmit.setEnabled(false);
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnTargets.setText("Targets");
        jbtnTargets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTargetsActionPerformed(evt);
            }
        });

        jbtnInstrCfgs.setText("Instrument Configs");
        jbtnInstrCfgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInstrCfgsActionPerformed(evt);
            }
        });

        jtpHelpPane.setEditable(false);
        jtpHelpPane.setText("Targets and Instrument Configs belong to Programmes rather than Proposals so that they may be used over many semesters without having to be re-entered.");
        jScrollPane1.setViewportView(jtpHelpPane);

        jbtnCancel.setForeground(new java.awt.Color(255, 0, 0));
        jbtnCancel.setText("Cancel");
        jbtnCancel.setEnabled(false);
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jbtnEdit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnSubmit)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnCancel))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jbtnTargets, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jbtnInstrCfgs))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jScrollPane1, 0, 0, Short.MAX_VALUE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jLabel1)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jLabel3)
                                .add(jLabel2))
                            .add(29, 29, 29)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jtfName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                                .add(jtfDescription, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(26, 26, 26)
                        .add(jLabel2))
                    .add(jtfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jtfDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jbtnTargets)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jbtnInstrCfgs)
                        .add(41, 41, 41)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jbtnEdit)
                            .add(jbtnSubmit)
                            .add(jbtnCancel))
                        .add(36, 36, 36))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 77, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed

    String name = jtfName.getText().trim();
    String description = jtfDescription.getText();
    
    if (name.length() == 0) {
        JOptionPane.showMessageDialog(this, "Please set a name for the programme.", "Submission failed", JOptionPane.OK_OPTION );
        return;
    }
    
    if (description.length() == 0) {
        JOptionPane.showMessageDialog(this, "Please set a description for the programme.", "Submission failed", JOptionPane.OK_OPTION );
        return;
    }

    Phase2ModelClient phase2ModelClient = Phase2ModelClient.getInstance();
    try {
       IProgram programWithName = phase2ModelClient.findProgram(name);
       if (programWithName != null) {
           if (programWithName.getID() != program.getID()) {
               //a different programme exists with this id
               JOptionPane.showMessageDialog(this, "A different programme exists with this name, please enter a different name.");
               return;
           }
       }
    } catch (Phase2Exception ex) {
        ex.printStackTrace();
        logger.error(ex);
        MainFrame.getInstance().enableTrees(true);
        return;
    }

    XProgram xProgram = (XProgram) program;
    xProgram.setName(name);
    xProgram.setDescription(description);
    
    final int KEY = 999;
    try {
        phase2ModelClient.updateProgramme(xProgram, KEY);
        MainFrame.getInstance().displayMessage("Edit Submitted.");
    } catch (Phase2Exception ex) {
        JOptionPane.showMessageDialog(this, "update failed: " + ex.getMessage());
        MainFrame.getInstance().enableTrees(true);
        return;
    }
    
    setEnabled(false);

    MainFrame.getInstance().enableTrees(true);
    MainFrame.getInstance().reloadSelectedNodeParent();
}//GEN-LAST:event_jbtnSubmitActionPerformed

private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
    MainFrame.getInstance().displayMessage("Editing Programme");
    setEnabled(true);
    MainFrame.getInstance().enableTrees(false);
}//GEN-LAST:event_jbtnEditActionPerformed

private void jbtnTargetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTargetsActionPerformed
    TargetListDialog  targetListDialog = new TargetListDialog(program);
    targetListDialog.setVisible(true);

    //blocks

    targetListDialog.setVisible(false);
    targetListDialog.dispose();
}//GEN-LAST:event_jbtnTargetsActionPerformed

private void jbtnInstrCfgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInstrCfgsActionPerformed
    InstrumentConfigListDialog  instrumentConfigListDialog = new InstrumentConfigListDialog(program);
    instrumentConfigListDialog.setVisible(true);

    //blocks

    instrumentConfigListDialog.setVisible(false);
    instrumentConfigListDialog.dispose();
}//GEN-LAST:event_jbtnInstrCfgsActionPerformed

private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
    setEnabled(false);

    MainFrame.getInstance().enableTrees(true);
    MainFrame.getInstance().reloadSelectedNodeParent();
}//GEN-LAST:event_jbtnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnInstrCfgs;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JButton jbtnTargets;
    private javax.swing.JTextField jtfDescription;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextPane jtpHelpPane;
    // End of variables declaration//GEN-END:variables

    
}
