/*
 * ProgrammeHeaderPanel.java
 *
 * Created on March 27, 2009, 2:54 PM
 */
package ngat.oss.client.gui.panel.headers;

import ngat.oss.client.gui.panel.interfaces.IEditablePanel;
import javax.swing.JOptionPane;
import ngat.oss.client.Phase2ModelClient;
import ngat.oss.client.gui.dialog.AccountsDialog;
import ngat.oss.client.gui.frame.MainFrame;
import ngat.oss.client.gui.reference.Session;
import ngat.oss.client.gui.util.LimitedCharactersDocument;
import ngat.oss.exception.Phase2Exception;
import ngat.phase2.ITag;
import ngat.phase2.XTag;
import org.apache.log4j.Logger;

/**
 *
 * @author  nrc
 */
public class TagHeaderPanel extends javax.swing.JPanel implements IEditablePanel {

    static Logger logger = Logger.getLogger(TagHeaderPanel.class);

    private ITag tag;
    private boolean enabled;

    public TagHeaderPanel(ITag tag) {
        this.tag = tag;
        initComponents();
        try {
            populateComponents();
        } catch (Exception ex) {
            ex.printStackTrace();
            logger.error(ex);
        }
        setEnabled(false);

    }

    private void populateComponents() throws Exception {
        jtfName.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.STRICT_LIMITATION));
        
        jtfName.setText(tag.getName());
    }

    public boolean isBeingEdited() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        
        jtfName.setEnabled(enabled);
        
        jbtnEdit.setEnabled(!enabled);
        jbtnSubmit.setEnabled(enabled);
        
        this.enabled = enabled;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnSubmit = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnAccounts = new javax.swing.JButton();

        jtfName.setFont(new java.awt.Font("Lucida Grande", 0, 10));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 10));
        jLabel1.setText("TAG");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("Name");

        jbtnSubmit.setForeground(new java.awt.Color(255, 0, 0));
        jbtnSubmit.setText("Submit");
        jbtnSubmit.setEnabled(false);
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnAccounts.setText("Accounts");
        jbtnAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAccountsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(jbtnEdit)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jbtnSubmit)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jbtnAccounts))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(jLabel2)
                            .add(56, 56, 56)
                            .add(jtfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 316, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(26, 26, 26)
                        .add(jLabel2))
                    .add(jtfName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jbtnEdit)
                    .add(jbtnSubmit)
                    .add(jbtnAccounts))
                .add(346, 346, 346))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed

     XTag xTag = (XTag) tag;
    
    //required fields: name, priority, active, timingConstraint, observingConstraints
    String name;
    
    name = jtfName.getText();
    
    if (name.length() == 0) {
        JOptionPane.showMessageDialog(this, "Please set a name for the TAG.", "Submission failed", JOptionPane.OK_OPTION );
        return;
    }
    
    xTag.setName(jtfName.getText());
    
    Phase2ModelClient phase2ModelClient = Phase2ModelClient.getInstance();
    
    final int KEY = 999;
    try {
        phase2ModelClient.updateTag(xTag, KEY);
        MainFrame.getInstance().displayMessage("TAG edit submitted");
    } catch (Phase2Exception ex) {
        JOptionPane.showMessageDialog(this, "update failed: " + ex.getMessage());
        MainFrame.getInstance().enableTrees(true);
        return;
    }
    
    setEnabled(false);

    MainFrame.getInstance().enableTrees(true);
    MainFrame.getInstance().reloadSelectedNodeParent();
}//GEN-LAST:event_jbtnSubmitActionPerformed

private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
    MainFrame.getInstance().displayMessage("Editing TAG " + tag.getName());
    setEnabled(true);
    MainFrame.getInstance().enableTrees(false);
}//GEN-LAST:event_jbtnEditActionPerformed

private void jbtnAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAccountsActionPerformed
    
    boolean allowAccountsEditing = Session.getInstance().getUser().isSuperUser();
    AccountsDialog dialog = new AccountsDialog(true, tag, allowAccountsEditing);
    dialog.setVisible(true);

    //blocks
    
    dialog.setVisible(false);
    dialog.dispose();
}//GEN-LAST:event_jbtnAccountsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnAccounts;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JTextField jtfName;
    // End of variables declaration//GEN-END:variables

    
}
