/*
 * SeeingConstraintPanel.java
 *
 * Created on 15 January 2008, 14:38
 */

package ngat.oss.client.gui.panel.observingConstraint;


import ngat.oss.client.gui.panel.interfaces.IObservingConstraintPanel;
import ngat.phase2.XAirmassConstraint;

/**
 *
 * @author  nrc
 */
public class AirMassObservingConstraintPanel extends javax.swing.JPanel implements IObservingConstraintPanel {
    
    private boolean enabled;
    private boolean delete;

    /** Creates new form SeeingConstraintPanel */
    public AirMassObservingConstraintPanel(XAirmassConstraint airmassConstraint, boolean newObsConstraint) {
        initComponents();
        setValues(airmassConstraint, newObsConstraint);
    }
    
    private void setValues(XAirmassConstraint airmassConstraint, boolean newObsConstraint) {
        jbtnDelete.setVisible(false);
        jtfMaximumElevation.setText("" + airmassConstraint.getMaximumAirmass());
    }
    
    public XAirmassConstraint getObservingConstraint() {
        return new XAirmassConstraint(Double.parseDouble(jtfMaximumElevation.getText()));
    }
    
    public boolean containsValidObservingConstraint() {
        try {
            Double.parseDouble(jtfMaximumElevation.getText());
        } catch (NumberFormatException nfe) {
            return false;
        }
        if (jtfMaximumElevation.getText().trim().length() == 0)
            return false;
        return true;
    }
    
    public boolean isEditable() {
        return enabled;
    }

    public void setEditable(boolean enabled) {
        this.enabled = enabled;

        jbtnDelete.setVisible(enabled);
        jtfMaximumElevation.setEnabled(enabled);
    }
    
    public boolean shouldBeDeleted() {
        return delete;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtfMaximumElevation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpHelpPane = new javax.swing.JTextPane();
        jbtnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Air Mass Constraint", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 10))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("AIR MASS <");

        jtfMaximumElevation.setColumns(3);
        jtfMaximumElevation.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jtfMaximumElevation.setText("2.0");

        jtpHelpPane.setEditable(false);
        jtpHelpPane.setText("This constraint is applied over the entire estimated length of the group.");
        jScrollPane1.setViewportView(jtpHelpPane);

        jbtnDelete.setText("Click to delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(4, 4, 4)
                        .add(jtfMaximumElevation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jbtnDelete)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 475, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtfMaximumElevation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jbtnDelete)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        if (!delete) {
            jbtnDelete.setText("Will be deleted, click to undelete");
            delete = true;
        } else {
            jbtnDelete.setText("Click to delete");
            delete = false;
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JTextField jtfMaximumElevation;
    private javax.swing.JTextPane jtpHelpPane;
    // End of variables declaration//GEN-END:variables

}
