/*
 * SeeingConstraintPanel.java
 *
 * Created on 15 January 2008, 14:38
 */

package ngat.oss.client.gui.panel.observingConstraint;


import ngat.oss.client.gui.panel.interfaces.IObservingConstraintPanel;
import ngat.phase2.XHourAngleConstraint;
import ngat.phase2.util.Rounder;
import ngat.phase2.util.UnitConverter;

/**
 *
 * @author  nrc
 */
public class HourAngleObservingConstraintPanel extends javax.swing.JPanel implements IObservingConstraintPanel {
    
    private boolean enabled;
    private boolean delete;

    public HourAngleObservingConstraintPanel(XHourAngleConstraint hourAngleConstraint, boolean newObsConstraint) {
        
        initComponents();
        setValues(hourAngleConstraint, newObsConstraint);
    }
    
    private void setValues(XHourAngleConstraint hourAngleConstraint, boolean newObsConstraint) {

        jbtnDelete.setVisible(false);
        jtfMinimumHourAngle.setText("" + Rounder.round(UnitConverter.convertRadsToHours(hourAngleConstraint.getMinimumHourAngle()),3));
        jtfMaximumHourAngle.setText("" + Rounder.round(UnitConverter.convertRadsToHours(hourAngleConstraint.getMaximumHourAngle()),3));
    }
    
    public XHourAngleConstraint getObservingConstraint() {
        double min =  UnitConverter.convertHoursToRads(Double.parseDouble(jtfMinimumHourAngle.getText()));
        double max = UnitConverter.convertHoursToRads(Double.parseDouble(jtfMaximumHourAngle.getText()));
        return new XHourAngleConstraint(min, max);
    }

    public boolean containsValidObservingConstraint() {
        if (jtfMinimumHourAngle.getText().trim().length() == 0)
            return false;
        if (jtfMaximumHourAngle.getText().trim().length() == 0)
            return false;
        
        return true;
    }
    
    public boolean isEditable() {
        return enabled;
    }

    public void setEditable(boolean enabled) {
        this.enabled = enabled;
        
        jtfMaximumHourAngle.setEnabled(enabled);
        jtfMinimumHourAngle.setEnabled(enabled);
        
       jbtnDelete.setVisible(enabled);
    }
    
    public boolean shouldBeDeleted() {
        return delete;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfMaximumHourAngle = new javax.swing.JTextField();
        jtfMinimumHourAngle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpHelpPane = new javax.swing.JTextPane();
        jbtnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hour Angle Constraint", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 10))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel1.setText("hours");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("< HOUR ANGLE < ");

        jtfMaximumHourAngle.setColumns(3);
        jtfMaximumHourAngle.setFont(new java.awt.Font("Lucida Grande", 0, 10));

        jtfMinimumHourAngle.setColumns(3);
        jtfMinimumHourAngle.setFont(new java.awt.Font("Lucida Grande", 0, 10));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel3.setText("hours");

        jtpHelpPane.setEditable(false);
        jtpHelpPane.setText("This constraint is applied at the start of the group.");
        jScrollPane1.setViewportView(jtpHelpPane);

        jbtnDelete.setText("Click to delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jtfMinimumHourAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2))
                            .add(layout.createSequentialGroup()
                                .add(47, 47, 47)
                                .add(jLabel3)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(jtfMaximumHourAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(37, 37, 37)
                                .add(jLabel1))))
                    .add(jbtnDelete)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
                .add(40, 40, 40))
        );

        layout.linkSize(new java.awt.Component[] {jtfMaximumHourAngle, jtfMinimumHourAngle}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtfMinimumHourAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtfMaximumHourAngle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnDelete)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        if (!delete) {
            jbtnDelete.setText("Will be deleted, click to undelete");
            delete = true;
        } else {
            jbtnDelete.setText("Click to delete");
            delete = false;
        }
}//GEN-LAST:event_jbtnDeleteActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JTextField jtfMaximumHourAngle;
    private javax.swing.JTextField jtfMinimumHourAngle;
    private javax.swing.JTextPane jtpHelpPane;
    // End of variables declaration//GEN-END:variables

}
