/*
 * SeeingConstraintPanel.java
 *
 * Created on 15 January 2008, 14:38
 */
package ngat.oss.client.gui.panel.observingConstraint;


import ngat.oss.client.gui.panel.interfaces.IObservingConstraintPanel;
import ngat.oss.client.gui.util.LimitedCharactersDocument;
import ngat.phase2.XSeeingConstraint;

/**
 *
 * @author  nrc
 */
public class SeeingObservingConstraintPanel extends javax.swing.JPanel implements IObservingConstraintPanel {

    private boolean enabled;
    private boolean delete;

    /** Seeing category, used to be one of:
    IObservingConstraint.GOOD_SEEING
    IObservingConstraint.AVERAGE_SEEING
    IObservingConstraint.POOR_SEEING
    IObservingConstraint.UNCONSTRAINED_SEEING
     */
    
    /** Creates new form SeeingConstraintPanel */
    public SeeingObservingConstraintPanel(XSeeingConstraint seeingConstraint, boolean newObsConstraint) {
        initComponents();

        jtfSeeingValue.setDocument(new LimitedCharactersDocument(LimitedCharactersDocument.NUMBERS_AND_DECPOINT_LIMITATION));

        setValues(seeingConstraint, newObsConstraint);
    }

    public XSeeingConstraint getObservingConstraint() {
        double seeingValue = Double.valueOf(jtfSeeingValue.getText());

        return new XSeeingConstraint(seeingValue);
    }

    public boolean containsValidObservingConstraint() {
        
        try {
            double seeingValue = Double.valueOf(jtfSeeingValue.getText());
            if ((seeingValue < 1) || (seeingValue > 5)) {
                return false;
            }
        } catch (NumberFormatException nfe) {
            return false;
        }
        
        return true;
    }
    
    private void setValues(XSeeingConstraint seeingConstraint, boolean newObsConstraint) {

        jbtnDelete.setVisible(false);

        jtfSeeingValue.setText( String.valueOf(seeingConstraint.getSeeingValue()));
       
    }

    public boolean isEditable() {
        return enabled;
    }

    public void setEditable(boolean enabled) {
        this.enabled = enabled;
        
        jbtnDelete.setVisible(enabled);
        jtfSeeingValue.setEnabled(enabled);
    }

    public boolean shouldBeDeleted() {
        return delete;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtpHelpPane = new javax.swing.JTextPane();
        jbtnDelete = new javax.swing.JButton();
        jtfSeeingValue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seeing Constraint", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 10))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("SEEING=");

        jLabel1.setText("arcsec or better");

        jtpHelpPane.setEditable(false);
        jtpHelpPane.setText("This constraint is applied at the start of the group and relates to the predicted r band seeing at the target elevation at the time of observation.\n(Please enter a value between 1.0 and 5.0, using only one decimal place.)\n");
        jScrollPane1.setViewportView(jtpHelpPane);

        jbtnDelete.setText("Click to delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jtfSeeingValue.setText("0.0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jbtnDelete)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtfSeeingValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel1)))
                .addContainerGap(217, Short.MAX_VALUE))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtfSeeingValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbtnDelete)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        if (!delete) {
            jbtnDelete.setText("Will be deleted, click to undelete");
            delete = true;
        } else {
            jbtnDelete.setText("Click to delete");
            delete = false;
        }
}//GEN-LAST:event_jbtnDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JTextField jtfSeeingValue;
    private javax.swing.JTextPane jtpHelpPane;
    // End of variables declaration//GEN-END:variables
}
